// Code generated by mockery v1.0.0. DO NOT EDIT.

package contract

import mock "github.com/stretchr/testify/mock"

// MockIdentifier is an autogenerated mock type for the Identifier type
type MockIdentifier struct {
	mock.Mock
}

// Id provides a mock function with given fields:
func (_m *MockIdentifier) Id() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
