// Code generated by mockery v1.0.0. DO NOT EDIT.

package contract

import mock "github.com/stretchr/testify/mock"

// MockChainabler is an autogenerated mock type for the Chainabler type
type MockChainabler struct {
	mock.Mock
}

// CanDenormalize provides a mock function with given fields: ref
func (_m *MockChainabler) CanDenormalize(ref string) bool {
	ret := _m.Called(ref)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(ref)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Denormalize provides a mock function with given fields: bag, ref, data
func (_m *MockChainabler) Denormalize(bag Bager, ref string, data map[string]interface{}) (Bager, error) {
	ret := _m.Called(bag, ref, data)

	var r0 Bager
	if rf, ok := ret.Get(0).(func(Bager, string, map[string]interface{}) Bager); ok {
		r0 = rf(bag, ref, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Bager)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Bager, string, map[string]interface{}) error); ok {
		r1 = rf(bag, ref, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
