// Code generated by mockery v1.0.0. DO NOT EDIT.

package contract

import mock "github.com/stretchr/testify/mock"

// MockCollectioner is an autogenerated mock type for the Collectioner type
type MockCollectioner struct {
	mock.Mock
}

// BuildIds provides a mock function with given fields: matches
func (_m *MockCollectioner) BuildIds(matches map[string]string) ([]string, error) {
	ret := _m.Called(matches)

	var r0 []string
	if rf, ok := ret.Get(0).(func(map[string]string) []string); ok {
		r0 = rf(matches)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(matches)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CanDenormalize provides a mock function with given fields: ref
func (_m *MockCollectioner) CanDenormalize(ref string) bool {
	ret := _m.Called(ref)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(ref)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Denormalize provides a mock function with given fields: ref, data
func (_m *MockCollectioner) Denormalize(ref string, data map[string]interface{}) (Bager, error) {
	ret := _m.Called(ref, data)

	var r0 Bager
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) Bager); ok {
		r0 = rf(ref, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Bager)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, map[string]interface{}) error); ok {
		r1 = rf(ref, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
