// Code generated by mockery v1.0.0. DO NOT EDIT.

package contract

import mock "github.com/stretchr/testify/mock"

// MockFixture is an autogenerated mock type for the Fixture type
type MockFixture struct {
	mock.Mock
}

// Fields provides a mock function with given fields:
func (_m *MockFixture) Fields() map[string]Value {
	ret := _m.Called()

	var r0 map[string]Value
	if rf, ok := ret.Get(0).(func() map[string]Value); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]Value)
		}
	}

	return r0
}

// Id provides a mock function with given fields:
func (_m *MockFixture) Id() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
